steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/round-cacao-444014-e3/gke-express-repo/gke-express:$SHORT_SHA
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - europe-west1-docker.pkg.dev/round-cacao-444014-e3/gke-express-repo/gke-express:$SHORT_SHA

  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-express-cluster'
    args:
      - set
      - image
      - deployment/gke-express-deployment
      - gke-express=europe-west1-docker.pkg.dev/round-cacao-444014-e3/gke-express-repo/gke-express:$SHORT_SHA

  - id: install-proxy
    name: gcr.io/gcp-runtimes/ubuntu_20_0_4
    entrypoint: bash
    args:
      - -c
      - |
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.14.1/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy
        ./cloud-sql-proxy --version

images:
  - 'europe-west1-docker.pkg.dev/round-cacao-444014-e3/gke-express-repo/gke-express:$SHORT_SHA'

substitutions:
  _DATABASE_NAME: express
  _INSTANCE_CONNECTION_NAME: round-cacao-444014-e3:europe-west1:gke-express-sql
  _DATABASE_PORT: '3306'

options:
  logging: CLOUD_LOGGING_ONLY
