steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/round-cacao-444014-e3/gke-express-repo/gke-express:$SHORT_SHA
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - europe-west1-docker.pkg.dev/round-cacao-444014-e3/gke-express-repo/gke-express:$SHORT_SHA

  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-express-cluster'
    args:
      - set
      - image
      - deployment/gke-express-deployment
      - gke-express=europe-west1-docker.pkg.dev/round-cacao-444014-e3/gke-express-repo/gke-express:$SHORT_SHA

  - id: install-proxy
    name: gcr.io/gcp-runtimes/ubuntu_20_0_4
    entrypoint: bash
    args:
      - -c
      - |
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.14.1/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy

  - id: migration
    name: flyway/flyway
    waitFor: ['install-proxy']
    entrypoint: bash
    secretEnv:
      - DATABASE_PASS
      - DATABASE_USER
    args:
      - -c
      - |
        ./cloud-sql-proxy ${_INSTANCE_CONNECTION_NAME} --port ${_DATABASE_PORT} & sleep 2
        flyway -url=jdbc:mysql://127.0.0.1:${_DATABASE_PORT}/${_DATABASE_NAME} -user=$$DATABASE_USER -password=$$DATABASE_PASS -locations=filesystem:/workspace/migrations migrate

images:
  - 'europe-west1-docker.pkg.dev/round-cacao-444014-e3/gke-express-repo/gke-express:$SHORT_SHA'

substitutions:
  _DATABASE_NAME: express
  _INSTANCE_CONNECTION_NAME: round-cacao-444014-e3:europe-west1:gke-express-sql
  _DATABASE_PORT: '3306'

availableSecrets:
  secretManager:
  - versionName: projects/round-cacao-444014-e3/secrets/sql_user/versions/latest
    env: 'DATABASE_USER'
  - versionName: projects/round-cacao-444014-e3/secrets/sql_pass/versions/latest
    env: 'DATABASE_PASS'

options:
  logging: CLOUD_LOGGING_ONLY
