apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-express-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gke-express
  template:
    metadata:
      labels:
        app: gke-express
    spec:
      serviceAccountName: gke-express-ksa
      containers:
      - name: gke-express
        image: europe-west1-docker.pkg.dev/round-cacao-444014-e3/gke-express-repo/gke-express:latest
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: gke-express-secret
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: gke-express-secret
                key: password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: gke-express-secret
                key: database
        ports:
        - containerPort: 8080
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.1
        args:
          - "--private-ip"
          - "--port=3306"
          - "round-cacao-444014-e3:europe-west1:gke-express-sql"
        securityContext:
          runAsNonRoot: true
